services:
  influxdb:
    container_name: cms-influxdb
    hostname: influxdb-service
    image: influxdb:2.7
    env_file:
      - ./.env
    volumes:
      - ./influxdb:/var/lib/influxdb2
    ports:
      - 8086:8086

  binance:
    container_name: cms-binance
    hostname: binance-service
    build:
      context: .
    depends_on:
      - influxdb
    env_file:
      - ./.env
    command:
      [
        "-x",
        "binance",
        "-m",
        "trades",
        "-s",
        "BTC/USDT",
        "-b",
        "400",
        "-l",
        "800",
      ]
