apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: crypto-market-recorder
build:
  artifacts:
    - image: registry.internal.visoft.solutions/crypto-market-recorder
      context: ./
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - ./k8s
