apiVersion: apps/v1
kind: Deployment
metadata:
  name: binance-deployment
  labels:
    app: binance
spec:
  selector:
    matchLabels:
      app: binance
  template:
    metadata:
      labels:
        app: binance
    spec:
      volumes:
        - name: influxdb-pv
          persistentVolumeClaim:
            claimName: influxdb-pvc
      containers:
        - name: binance
          image: registry.internal.visoft.solutions/crypto-market-recorder
          envFrom:
            - secretRef:
                name: secrets
            - configMapRef:
                name: config
          volumeMounts:
            - mountPath: /var/lib/influxdb2
              name: influxdb-pv
          command:
            [
              "python",
              "src/main.py",
              "-x",
              "binance",
              "-m",
              "trades",
              "-s",
              "BTC/USDT",
              "ETH/USDT",
              "MATIC/USDT",
              "DOT/USDT",
              "WAVES/USDT",
              "ADA/USDT",
              "FTM/USDT",
              "-b",
              "400",
              "-l",
              "800",
            ]
          resources:
            requests:
              memory: 200Mi
              cpu: 200m
            limits:
              memory: 300Mi
              cpu: 300m
