apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
spec:
  storageClassName: rook-ceph-ec-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
