apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crypto-market-recorder

resources:
  - ./resources/influxdb.yaml
  - ./resources/binance.yaml

secretGenerator:
  - name: secrets
    env: ./secrets.env

configMapGenerator:
  - name: config
    env: ./config.env

generatorOptions:
  disableNameSuffixHash: true
